language: android
jdk: oraclejdk7

android:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

  components:
    # The BuildTools version used by your project
    - build-tools-20.0.0
    - android-19

    # Additional components
    - extra-android-m2repository
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- addon-google_apis-google-19

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assemble